# @package _global_
general:
  num_devices: 1
  mixed_precision: true

data:
  znear: 0.8
  zfar: 3.2
  category: front3d
  white_background: true
  origin_distances: false
  training_resolution: 128
  fov: 49.134342641202636

opt:
  batch_size: 1
  iterations: 30
